url: https://claudiuandrei.com

# Site settings
title: Claudiu Andrei
description: "I love to build great applications"

# Contact
email: claudiu.andrei@gmail.com
phone: (650) 937-9397
address: San Diego, CA


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
github: http://github.com/claudiuandrei

# Build settings
markdown: kramdown
permalink: pretty